// services/estimatePdf.js — lightweight, coded-layout PDF (pdfkit, no browser engine).
// Deliberately not a literal copy of the web view's design — this has its own simpler
// layout, built for print rather than screen.
const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

// Brand colors pulled from the Connected Home Outfitters WordPress site's Elementor
// global kit (system_colors) — kept in sync with public/css/portal.css's CSS
// variables and views/emails' inline styles, since pdfkit can't share a stylesheet.
const BRAND = {
  accent: '#0799D6',
  primary: '#6EC1E4',
  dark: '#54595F',
  text: '#7A7A7A',
};

const LOGO_PATH = path.join(__dirname, '../public/img/logo.png');

function money(n) {
  return `$${Number(n).toFixed(2)}`;
}

// Returns a Promise<Buffer> — buffered in memory rather than streamed, since estimate
// PDFs are small (one page, plain text/tables) and this needs to work both as an email
// attachment and as an HTTP download from the same generated bytes.
function generateEstimatePdf({ estimate, items, customer, company = {} }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // The tenant's own logo when they've uploaded one, else the bundled default. Wrapped
    // because a missing/corrupt upload must not fail the whole PDF — pdfkit throws on an
    // unreadable image, and an estimate without a logo still beats no estimate.
    try {
      const logo = (company.logo_file && fs.existsSync(company.logo_file))
        ? company.logo_file
        : LOGO_PATH;
      doc.image(logo, 50, 45, { width: 180 });
    } catch (err) {
      console.error('estimatePdf: logo render failed, continuing without it:', err.message);
    }

    // Company identity block, top-right (name/address/phone/email/tax ID from
    // company_settings) — makes the estimate a proper business document.
    const companyName = company.company_name || 'Connected Home Outfitters LLC';
    const coLines = [companyName];
    if (company.address) coLines.push(company.address);
    const contact = [company.phone, company.email].filter(Boolean).join(' · ');
    if (contact) coLines.push(contact);
    if (company.tax_id) coLines.push(`Tax ID: ${company.tax_id}`);
    doc.fontSize(8).fillColor(BRAND.dark);
    doc.text(coLines[0], 300, 48, { width: 245, align: 'right' });
    if (coLines.length > 1) {
      doc.fillColor(BRAND.text).text(coLines.slice(1).join('\n'), 300, doc.y, { width: 245, align: 'right' });
    }

    doc.moveTo(50, 100).lineTo(545, 100).strokeColor(BRAND.primary).lineWidth(2).stroke();
    doc.y = 112;

    doc.fillColor(BRAND.dark).fontSize(14).text(estimate.title);
    if (estimate.description) {
      doc.fontSize(10).fillColor(BRAND.text).text(estimate.description);
    }
    doc.moveDown();

    doc.fontSize(10).fillColor('#000');
    doc.text(`Prepared for: ${customer.name}`);
    if (customer.address) doc.text(customer.address);
    if (customer.email) doc.text(customer.email);
    if (customer.phone) doc.text(customer.phone);
    doc.moveDown(1.5);

    if (estimate.flat_price != null) {
      // Flat-rate package: the customer sees what's included, with no per-line pricing.
      if (items.length) {
        doc.fontSize(11).fillColor(BRAND.dark).text('This package includes:');
        doc.moveDown(0.3);
        doc.fontSize(10).fillColor('#000');
        for (const item of items) {
          doc.text(`•  ${item.description}`, { indent: 10 });
        }
      }
      doc.moveDown(0.6);
      doc.moveTo(50, doc.y + 3).lineTo(545, doc.y + 3).strokeColor('#ccc').stroke();
      doc.moveDown(0.8);
      // Flat price is pre-tax; sales tax (if any) is charged on the taxable goods only.
      doc.fontSize(10).fillColor('#000').text(`Package price: ${money(estimate.flat_price)}`, { align: 'right' });
      if (Number(estimate.tax) > 0) {
        doc.text(`Sales tax: ${money(estimate.tax)}`, { align: 'right' });
      }
      doc.fontSize(13).fillColor(BRAND.accent).text(`Total: ${money(estimate.total)}`, { align: 'right' });
    } else {
      // Line items table — simple fixed-column layout, no external table library.
      const colX = { desc: 50, qty: 350, price: 410, total: 480 };
      doc.fontSize(10).fillColor(BRAND.dark);
      doc.text('Description', colX.desc, doc.y, { continued: false });
      doc.text('Qty', colX.qty, doc.y - doc.currentLineHeight());
      doc.text('Price', colX.price, doc.y - doc.currentLineHeight());
      doc.text('Total', colX.total, doc.y - doc.currentLineHeight());
      doc.moveTo(50, doc.y + 3).lineTo(545, doc.y + 3).strokeColor(BRAND.primary).stroke();
      doc.moveDown(0.5);

      for (const item of items) {
        // A hidden-price line shows "Included" to the customer instead of a dollar amount
        // (its cost still counts toward the estimate subtotal/total).
        const rowY = doc.y;
        doc.fontSize(10).fillColor('#000');
        doc.text(item.description, colX.desc, rowY, { width: 290 });
        const afterDescY = doc.y;
        doc.text(String(item.quantity), colX.qty, rowY);
        if (item.hide_price) {
          doc.fillColor(BRAND.text).text('Included', colX.price, rowY);
          doc.fillColor('#000');
        } else {
          doc.text(money(item.unit_price), colX.price, rowY);
          doc.text(money(item.quantity * item.unit_price), colX.total, rowY);
        }
        doc.y = Math.max(afterDescY, rowY + doc.currentLineHeight());
        doc.moveDown(0.3);
      }

      doc.moveTo(50, doc.y + 3).lineTo(545, doc.y + 3).strokeColor('#ccc').stroke();
      doc.moveDown(0.8);

      doc.fontSize(10).fillColor('#000');
      doc.text(`Subtotal: ${money(estimate.subtotal)}`, { align: 'right' });
      doc.text(`Tax: ${money(estimate.tax)}`, { align: 'right' });
      doc.fontSize(13).fillColor(BRAND.accent).text(`Total: ${money(estimate.total)}`, { align: 'right' });
    }

    doc.moveDown(0.5);
    doc.fontSize(10).fillColor(BRAND.text).text(
      `Deposit due to begin (${estimate.deposit_percent}%): ${money(estimate.deposit_amount)}`,
      { align: 'right' }
    );

    doc.moveDown(2);
    doc.fontSize(8).fillColor(BRAND.text).text(
      'This estimate is valid for 30 days from the date sent. Final pricing may vary based on ' +
      'on-site conditions discovered during installation.',
      { align: 'left' }
    );

    doc.end();
  });
}

module.exports = { generateEstimatePdf };
