#!/usr/bin/env node
'use strict';
// Renders marketing/src/*.ejs into plain .html at marketing/, and generates sitemap.xml
// from the same page manifest.
//
// Why a build step at all: the site outgrew one hand-written file, and six copies of the
// masthead would drift within a week. Why not render at request time: nginx serves this
// directory with no process behind it, which is what makes a mistake here unable to take
// the product down. Building keeps that property and removes the duplication.
//
// The generated .html IS committed — nginx serves the repo checkout directly, so a deploy
// is still `git pull` with nothing to run on the server.
//
//   npm run marketing:build

const fs = require('fs');
const path = require('path');
const ejs = require('ejs');

const SRC = path.join(__dirname, 'src');
const OUT = __dirname;
const ORIGIN = 'https://connectedworkos.com';

const pages = require('./src/_pages.js');
const layout = path.join(SRC, '_layout.ejs');

function build() {
  const nav = pages.filter(p => p.nav).map(p => ({ url: p.url, label: p.nav }));
  let written = 0;

  for (const page of pages) {
    const src = path.join(SRC, `${page.slug}.ejs`);
    if (!fs.existsSync(src)) {
      // Loud, not silent: a manifest entry with no template would otherwise ship a
      // sitemap URL that 404s, which is worse than failing the build.
      throw new Error(`Manifest lists "${page.slug}" but ${path.relative(OUT, src)} does not exist`);
    }

    const body = ejs.render(fs.readFileSync(src, 'utf8'), { page, pages, nav, ORIGIN }, { filename: src });
    const html = ejs.render(fs.readFileSync(layout, 'utf8'), { page, pages, nav, ORIGIN, body }, { filename: layout });

    fs.writeFileSync(path.join(OUT, `${page.slug}.html`), html);
    written++;
  }

  // Sitemap from the same list, so a page can never be built but left unlisted.
  const today = new Date().toISOString().slice(0, 10);
  const urls = pages.map(p => `  <url>
    <loc>${ORIGIN}${p.url}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>${p.changefreq}</changefreq>
    <priority>${p.priority}</priority>
  </url>`).join('\n');

  fs.writeFileSync(path.join(OUT, 'sitemap.xml'),
`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by marketing/build.js from src/_pages.js. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`);

  console.log(`built ${written} page(s) + sitemap.xml (${pages.length} urls)`);
}

build();
